package seeder

import (
	"log"
	"time"

	"web_doscom/internal/auth"
	"web_doscom/internal/database/model/entity"

	"gorm.io/gorm"
)

func SeedUsers(db *gorm.DB) {
	now := time.Now()

	passwordHash := auth.HashPassword("password123")

	users := []entity.User{
		{
			Username:  "aldio",
			Email:     "111202315460@mhs.dinus.ac.id",
			Full_name: "Aldio Sebastiansyah",
			Password:  passwordHash,
			Role:      "SuperAdmin",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "imam",
			Email:     "111202314916@mhs.dinus.ac.id",
			Full_name: "Muhammad Imam Rafi",
			Password:  passwordHash,
			Role:      "BPH",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "ivan",
			Email:     "111202314933@mhs.dinus.ac.id",
			Full_name: "Muhammad Ivan Rafsanjani",
			Password:  passwordHash,
			Role:      "BPH",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "desvita",
			Email:     "111202315298@mhs.dinus.ac.id",
			Full_name: "Desvita Maharani",
			Password:  passwordHash,
			Role:      "BPH",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "inas",
			Email:     "112202407184@mhs.dinus.ac.id",
			Full_name: "Inas Salwa Nuraini",
			Password:  passwordHash,
			Role:      "BPH",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "maxentia",
			Email:     "111202315443@mhs.dinus.ac.id",
			Full_name: "Maxentia Kathleen",
			Password:  passwordHash,
			Role:      "BPH",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "widya",
			Email:     "111202415648@mhs.dinus.ac.id",
			Full_name: "Widya Allifya Az Zahra",
			Password:  passwordHash,
			Role:      "BPH",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "harry",
			Email:     "111202315332@mhs.dinus.ac.id",
			Full_name: "Harry LBI",
			Password:  passwordHash,
			Role:      "BPH",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "fadhil",
			Email:     "111202415691@mhs.dinus.ac.id",
			Full_name: "Fadhil Riyanto",
			Password:  passwordHash,
			Role:      "BPH",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "wildanu",
			Email:     "111202314978@mhs.dinus.ac.id",
			Full_name: "Wildanu Rafif Albaihaqi",
			Password:  passwordHash,
			Role:      "BPH",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "sulthan",
			Email:     "111202315253@mhs.dinus.ac.id",
			Full_name: "Sulthan Yustr Suwardhi",
			Password:  passwordHash,
			Role:      "BPHAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "wilma",
			Email:     "111202415841@mhs.dinus.ac.id",
			Full_name: "Wilma Auraruna Khalif",
			Password:  passwordHash,
			Role:      "BPHAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "danish",
			Email:     "111202415566@mhs.dinus.ac.id",
			Full_name: "Danish Putra Utama",
			Password:  passwordHash,
			Role:      "BPHAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "dhion",
			Email:     "111202315448@mhs.dinus.ac.id",
			Full_name: "Dhion Nur Damanhuri",
			Password:  passwordHash,
			Role:      "KoorMedcrev",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "mohammad",
			Email:     "111202315034@mhs.dinus.ac.id",
			Full_name: "Mohammad Fikri Haikal",
			Password:  passwordHash,
			Role:      "medcrevAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "megan",
			Email:     "111202315039@mhs.dinus.ac.id",
			Full_name: "Megan Febriana Putri Johana",
			Password:  passwordHash,
			Role:      "medcrevAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "garneta",
			Email:     "114202304209@mhs.dinus.ac.id",
			Full_name: "Garneta Ary Yuwaningtyas",
			Password:  passwordHash,
			Role:      "medcrevAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "reno",
			Email:     "111202315017@mhs.dinus.ac.id",
			Full_name: "Reno Dwi Aderelyan",
			Password:  passwordHash,
			Role:      "medcrevAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "nayzala",
			Email:     "112202407174@mhs.dinus.ac.id",
			Full_name: "Nayzala Aura Riyana",
			Password:  passwordHash,
			Role:      "medcrevAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "elsandro",
			Email:     "111202415895@mhs.dinus.ac.id",
			Full_name: "Elsandro Rivalito",
			Password:  passwordHash,
			Role:      "medcrevAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "fatah",
			Email:     "114202404506@mhs.dinus.ac.id",
			Full_name: "Fatah Al Farid",
			Password:  passwordHash,
			Role:      "medcrevAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "zovan",
			Email:     "111202415585@mhs.dinus.ac.id",
			Full_name: "Zovan Rizza Fannevi",
			Password:  passwordHash,
			Role:      "medcrevAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "jovandya",
			Email:     "111202415989@mhs.dinus.ac.id",
			Full_name: "Jovandya Ardhika",
			Password:  passwordHash,
			Role:      "medcrevAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "amelia",
			Email:     "111202415661@mhs.dinus.ac.id",
			Full_name: "Amelia Ramadhani",
			Password:  passwordHash,
			Role:      "medcrevAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "suryani",
			Email:     "111202315018@mhs.dinus.ac.id",
			Full_name: "Suryani Ayu Dewanti",
			Password:  passwordHash,
			Role:      "medcrevAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "jonathan",
			Email:     "111202315244@mhs.dinus.ac.id",
			Full_name: "Jonathan Naufal Farrel",
			Password:  passwordHash,
			Role:      "medcrevAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "dian",
			Email:     "111202315203@mhs.dinus.ac.id",
			Full_name: "Dian Hana Kartiko Sari",
			Password:  passwordHash,
			Role:      "medcrevAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "adhifa",
			Email:     "111202415836@mhs.dinus.ac.id",
			Full_name: "Adhifa fairuz zulfi",
			Password:  passwordHash,
			Role:      "medcrevAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "rico",
			Email:     "111202315393@mhs.dinus.ac.id",
			Full_name: "Rico Andre Pratama",
			Password:  passwordHash,
			Role:      "KoorPemro",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "felixs",
			Email:     "111202315458@mhs.dinus.ac.id",
			Full_name: "Felixs Togar Nugroho Siahaan",
			Password:  passwordHash,
			Role:      "pemroAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "husnul",
			Email:     "111202415776@mhs.dinus.ac.id",
			Full_name: "Husnul Fikri Averus",
			Password:  passwordHash,
			Role:      "pemroAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "naf'an",
			Email:     "111202415651@mhs.dinus.ac.id",
			Full_name: "Naf'an Nur'alim",
			Password:  passwordHash,
			Role:      "pemroAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "rizki",
			Email:     "111202415546@mhs.dinus.ac.id",
			Full_name: "Rizki Ardiansyah Novianto",
			Password:  passwordHash,
			Role:      "pemroAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "bagus",
			Email:     "111202416082@mhs.dinus.ac.id",
			Full_name: "Muhammad Bagus Aditya",
			Password:  passwordHash,
			Role:      "pemroAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "jessica",
			Email:     "111202415833@mhs.dinus.ac.id",
			Full_name: "Jessica Leilani Handoko",
			Password:  passwordHash,
			Role:      "pemroAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "ilham",
			Email:     "111202415656@mhs.dinus.ac.id",
			Full_name: "Muhammad Ilham Maulana",
			Password:  passwordHash,
			Role:      "pemroAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "ghifari",
			Email:     "111202415775@mhs.dinus.ac.id",
			Full_name: "Ghifari Wira Andanito",
			Password:  passwordHash,
			Role:      "pemroAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "fa'iz",
			Email:     "111202415726@mhs.dinus.ac.id",
			Full_name: "Fa'iz Maulana Habibi",
			Password:  passwordHash,
			Role:      "pemroAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "fajar 2",
			Email:     "111202415685@mhs.dinus.ac.id",
			Full_name: "Fajar Aziz Kurniawan",
			Password:  passwordHash,
			Role:      "pemroAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "fariz",
			Email:     "111202315467@mhs.dinus.ac.id",
			Full_name: "Fariz Hasim Arvianto",
			Password:  passwordHash,
			Role:      "KoorData",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "brenendra",
			Email:     "111202315020@mhs.dinus.ac.id",
			Full_name: "Brenendra Putra Oktaviansyah",
			Password:  passwordHash,
			Role:      "dataAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "johana",
			Email:     "111202315024@mhs.dinus.ac.id",
			Full_name: "Johana Oktavia Ramadhani",
			Password:  passwordHash,
			Role:      "dataAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "chalida",
			Email:     "111202315031@mhs.dinus.ac.id",
			Full_name: "Chalida Abdat",
			Password:  passwordHash,
			Role:      "dataAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "naya",
			Email:     "111202315212@mhs.dinus.ac.id",
			Full_name: "Naya Nasywa Puspita Haryanto",
			Password:  passwordHash,
			Role:      "dataAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "berlian",
			Email:     "111202315247@mhs.dinus.ac.id",
			Full_name: "Berlian Kusumayuda",
			Password:  passwordHash,
			Role:      "dataAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "daniyal",
			Email:     "111202315367@mhs.dinus.ac.id",
			Full_name: "Muhammad Daniyal Haq",
			Password:  passwordHash,
			Role:      "KoorJaringan",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "yuanda",
			Email:     "111202314944@mhs.dinus.ac.id",
			Full_name: "Yuanda Kusuma Aji",
			Password:  passwordHash,
			Role:      "jaringanAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "mawahib",
			Email:     "111202315462@mhs.dinus.ac.id",
			Full_name: "Muhammad Ni'am Mawahib",
			Password:  passwordHash,
			Role:      "jaringanAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "arbinand",
			Email:     "112202307051@mhs.dinus.ac.id",
			Full_name: "Arbinand Roffi Ilmi",
			Password:  passwordHash,
			Role:      "jaringanAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "faiz",
			Email:     "111202315400@mhs.dinus.ac.id",
			Full_name: "Faiz Aditya Dhananjaya",
			Password:  passwordHash,
			Role:      "jaringanAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "arya",
			Email:     "111202315457@mhs.dinus.ac.id",
			Full_name: "Arya Pradipta",
			Password:  passwordHash,
			Role:      "jaringanAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "cherishta",
			Email:     "111202416045@mhs.dinus.ac.id",
			Full_name: "Cherishta Joane Nungki",
			Password:  passwordHash,
			Role:      "jaringanAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "fujikawa",
			Email:     "111202415662@mhs.dinus.ac.id",
			Full_name: "Fujikawa Shinichi",
			Password:  passwordHash,
			Role:      "jaringanAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "aldi",
			Email:     "111202415935@mhs.dinus.ac.id",
			Full_name: "Aldi Firmansyah",
			Password:  passwordHash,
			Role:      "jaringanAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "nicko",
			Email:     "111202415690@mhs.dinus.ac.id",
			Full_name: "Nicko Galang Anarki",
			Password:  passwordHash,
			Role:      "jaringanAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "haikal",
			Email:     "111202415805@mhs.dinus.ac.id",
			Full_name: "Haikal Ega Pratama",
			Password:  passwordHash,
			Role:      "jaringanAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "fajar 1",
			Email:     "111202415561@mhs.dinus.ac.id",
			Full_name: "Fajar Maulana P",
			Password:  passwordHash,
			Role:      "jaringanAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "naufal",
			Email:     "111202415571@mhs.dinus.ac.id",
			Full_name: "Muhammad Naufal Tsaqif",
			Password:  passwordHash,
			Role:      "jaringanAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "raditya",
			Email:     "111202415718@mhs.dinus.ac.id",
			Full_name: "Raditya Perwira Putra",
			Password:  passwordHash,
			Role:      "jaringanAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "danendra",
			Email:     "111202315025@mhs.dinus.ac.id",
			Full_name: "Danendra Farrel Haryo Wibowo",
			Password:  passwordHash,
			Role:      "jaringanAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
		{
			Username:  "ferdynand",
			Email:     "111202315389@mhs.dinus.ac.id",
			Full_name: "Ferdynand Ergy Pramudani",
			Password:  passwordHash,
			Role:      "jaringanAnggota",
			CreatedAt: now,
			UpdatedAt: now,
		},
	}

	for i := range users {
		result := db.Where("email = ?", users[i].Email).FirstOrCreate(&users[i])

		if result.Error != nil {
			log.Printf("failed seed user email=%s: %v", users[i].Email, result.Error)
			return
		}
	}

	log.Println("Seed table 'users' completed.")
}
